### ISSUE TITLE
Caffemodel

### ISSUE THREAD

**Issue by ghost** [arzavj/deepMammo#2]
I'm trying to recreate some of the results here using the googlenet model. You've dumped the weights as a pickle file yet Caffe can't read that in to initialize the net. Do you have the caffemodels or is there something I'm missing?

**Comment by arzavj** [comment]
The pickle files were only used to serialize the train/val loss & accuracy for plotting purposes. The weights files (*.caffemodel) were not included in the repo because they were relatively big. And unfortunately I don't have them locally anymore since we worked on a remote instance.
